/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as AuthenticatedPoolsIndexRouteImport } from './routes/_authenticated.pools.index'
import { Route as AuthenticatedPoolsNewRouteImport } from './routes/_authenticated.pools.new'
import { Route as AuthenticatedPoolsIdRouteImport } from './routes/_authenticated.pools.$id'
import { Route as AuthenticatedPoolsIdPredictRouteImport } from './routes/_authenticated.pools.$id.predict'
import { Route as AuthenticatedPoolsIdPrizesEditRouteImport } from './routes/_authenticated.pools.$id.prizes.edit'
import { Route as AuthenticatedPoolsIdPredictMatchIdRouteImport } from './routes/_authenticated.pools.$id.predict.$matchId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPoolsIndexRoute = AuthenticatedPoolsIndexRouteImport.update({
  id: '/pools/',
  path: '/pools/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPoolsNewRoute = AuthenticatedPoolsNewRouteImport.update({
  id: '/pools/new',
  path: '/pools/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPoolsIdRoute = AuthenticatedPoolsIdRouteImport.update({
  id: '/pools/$id',
  path: '/pools/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPoolsIdPredictRoute =
  AuthenticatedPoolsIdPredictRouteImport.update({
    id: '/predict',
    path: '/predict',
    getParentRoute: () => AuthenticatedPoolsIdRoute,
  } as any)
const AuthenticatedPoolsIdPrizesEditRoute =
  AuthenticatedPoolsIdPrizesEditRouteImport.update({
    id: '/prizes/edit',
    path: '/prizes/edit',
    getParentRoute: () => AuthenticatedPoolsIdRoute,
  } as any)
const AuthenticatedPoolsIdPredictMatchIdRoute =
  AuthenticatedPoolsIdPredictMatchIdRouteImport.update({
    id: '/$matchId',
    path: '/$matchId',
    getParentRoute: () => AuthenticatedPoolsIdPredictRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/join/$code': typeof JoinCodeRoute
  '/pools/$id': typeof AuthenticatedPoolsIdRouteWithChildren
  '/pools/new': typeof AuthenticatedPoolsNewRoute
  '/pools/': typeof AuthenticatedPoolsIndexRoute
  '/pools/$id/predict': typeof AuthenticatedPoolsIdPredictRouteWithChildren
  '/pools/$id/predict/$matchId': typeof AuthenticatedPoolsIdPredictMatchIdRoute
  '/pools/$id/prizes/edit': typeof AuthenticatedPoolsIdPrizesEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/join/$code': typeof JoinCodeRoute
  '/': typeof AuthenticatedIndexRoute
  '/pools/$id': typeof AuthenticatedPoolsIdRouteWithChildren
  '/pools/new': typeof AuthenticatedPoolsNewRoute
  '/pools': typeof AuthenticatedPoolsIndexRoute
  '/pools/$id/predict': typeof AuthenticatedPoolsIdPredictRouteWithChildren
  '/pools/$id/predict/$matchId': typeof AuthenticatedPoolsIdPredictMatchIdRoute
  '/pools/$id/prizes/edit': typeof AuthenticatedPoolsIdPrizesEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/join/$code': typeof JoinCodeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/pools/$id': typeof AuthenticatedPoolsIdRouteWithChildren
  '/_authenticated/pools/new': typeof AuthenticatedPoolsNewRoute
  '/_authenticated/pools/': typeof AuthenticatedPoolsIndexRoute
  '/_authenticated/pools/$id/predict': typeof AuthenticatedPoolsIdPredictRouteWithChildren
  '/_authenticated/pools/$id/predict/$matchId': typeof AuthenticatedPoolsIdPredictMatchIdRoute
  '/_authenticated/pools/$id/prizes/edit': typeof AuthenticatedPoolsIdPrizesEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/join/$code'
    | '/pools/$id'
    | '/pools/new'
    | '/pools/'
    | '/pools/$id/predict'
    | '/pools/$id/predict/$matchId'
    | '/pools/$id/prizes/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/join/$code'
    | '/'
    | '/pools/$id'
    | '/pools/new'
    | '/pools'
    | '/pools/$id/predict'
    | '/pools/$id/predict/$matchId'
    | '/pools/$id/prizes/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/join/$code'
    | '/_authenticated/'
    | '/_authenticated/pools/$id'
    | '/_authenticated/pools/new'
    | '/_authenticated/pools/'
    | '/_authenticated/pools/$id/predict'
    | '/_authenticated/pools/$id/predict/$matchId'
    | '/_authenticated/pools/$id/prizes/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  JoinCodeRoute: typeof JoinCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pools/': {
      id: '/_authenticated/pools/'
      path: '/pools'
      fullPath: '/pools/'
      preLoaderRoute: typeof AuthenticatedPoolsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pools/new': {
      id: '/_authenticated/pools/new'
      path: '/pools/new'
      fullPath: '/pools/new'
      preLoaderRoute: typeof AuthenticatedPoolsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pools/$id': {
      id: '/_authenticated/pools/$id'
      path: '/pools/$id'
      fullPath: '/pools/$id'
      preLoaderRoute: typeof AuthenticatedPoolsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pools/$id/predict': {
      id: '/_authenticated/pools/$id/predict'
      path: '/predict'
      fullPath: '/pools/$id/predict'
      preLoaderRoute: typeof AuthenticatedPoolsIdPredictRouteImport
      parentRoute: typeof AuthenticatedPoolsIdRoute
    }
    '/_authenticated/pools/$id/prizes/edit': {
      id: '/_authenticated/pools/$id/prizes/edit'
      path: '/prizes/edit'
      fullPath: '/pools/$id/prizes/edit'
      preLoaderRoute: typeof AuthenticatedPoolsIdPrizesEditRouteImport
      parentRoute: typeof AuthenticatedPoolsIdRoute
    }
    '/_authenticated/pools/$id/predict/$matchId': {
      id: '/_authenticated/pools/$id/predict/$matchId'
      path: '/$matchId'
      fullPath: '/pools/$id/predict/$matchId'
      preLoaderRoute: typeof AuthenticatedPoolsIdPredictMatchIdRouteImport
      parentRoute: typeof AuthenticatedPoolsIdPredictRoute
    }
  }
}

interface AuthenticatedPoolsIdPredictRouteChildren {
  AuthenticatedPoolsIdPredictMatchIdRoute: typeof AuthenticatedPoolsIdPredictMatchIdRoute
}

const AuthenticatedPoolsIdPredictRouteChildren: AuthenticatedPoolsIdPredictRouteChildren =
  {
    AuthenticatedPoolsIdPredictMatchIdRoute:
      AuthenticatedPoolsIdPredictMatchIdRoute,
  }

const AuthenticatedPoolsIdPredictRouteWithChildren =
  AuthenticatedPoolsIdPredictRoute._addFileChildren(
    AuthenticatedPoolsIdPredictRouteChildren,
  )

interface AuthenticatedPoolsIdRouteChildren {
  AuthenticatedPoolsIdPredictRoute: typeof AuthenticatedPoolsIdPredictRouteWithChildren
  AuthenticatedPoolsIdPrizesEditRoute: typeof AuthenticatedPoolsIdPrizesEditRoute
}

const AuthenticatedPoolsIdRouteChildren: AuthenticatedPoolsIdRouteChildren = {
  AuthenticatedPoolsIdPredictRoute:
    AuthenticatedPoolsIdPredictRouteWithChildren,
  AuthenticatedPoolsIdPrizesEditRoute: AuthenticatedPoolsIdPrizesEditRoute,
}

const AuthenticatedPoolsIdRouteWithChildren =
  AuthenticatedPoolsIdRoute._addFileChildren(AuthenticatedPoolsIdRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPoolsIdRoute: typeof AuthenticatedPoolsIdRouteWithChildren
  AuthenticatedPoolsNewRoute: typeof AuthenticatedPoolsNewRoute
  AuthenticatedPoolsIndexRoute: typeof AuthenticatedPoolsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPoolsIdRoute: AuthenticatedPoolsIdRouteWithChildren,
  AuthenticatedPoolsNewRoute: AuthenticatedPoolsNewRoute,
  AuthenticatedPoolsIndexRoute: AuthenticatedPoolsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  JoinCodeRoute: JoinCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
