-- [SECURITY NOTICE] 
-- The content of this migration was moved to a new secure migration 
-- because it contained a hardcoded service_role key. 
-- The cron jobs have been unscheduled and recreated using the 
-- Supabase Vault pattern to protect the project's secrets.
